apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  namespace: "{{ .Values.general.namespace }}"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      nodePort: 30190
  selector:
    app: "{{ .Chart.Name }}"
  type: NodePort